mod decode;
mod hosting;
mod model;
mod spore_capnp; // generated by build.rs

use anyhow::{Context, Result};
use decode::SporeStream;
use tokio::task;

#[tokio::main]
async fn main() -> Result<()> {
    let configs = task::spawn_blocking(|| SporeStream::from_stdin().collect::<Vec<_>>())
        .await
        .context("spore reader task failed")?;

    for item in configs {
        let config = item.context("failed to decode spore")?;
        config
            .hosting_designation
            .apply(&config)
            .await
            .context("failed to apply hosting designation")?;
        println!(
            "Mycelia Spore: processed configuration for {}",
            config.site_identity.canonical_id
        );
    }
    Ok(())
}
