mod spore_capnp; // generated by build.rs
mod model;
mod decode;
mod hosting;

use anyhow::{Context, Result};
use decode::spore_stream;
use hosting::apply_hosting;

fn main() -> Result<()> {
    for item in spore_stream() {
        let config = item.context("failed to decode spore")?;
        apply_hosting(&config).context("failed to apply hosting")?;
        println!("Mycelia Spore: hosting updated for site {}", config.site.id);
    }
    Ok(())
}
