mod decode;
mod hosting;
mod model;
mod spore_capnp; // generated by build.rs

use anyhow::{Context, Result};
use decode::SporeStream;
use tokio::task;

#[tokio::main]
async fn main() -> Result<()> {
    let configs = task::spawn_blocking(|| SporeStream::from_stdin().collect::<Vec<_>>())
        .await
        .context("spore reader task failed")?;

    for item in configs {
        let config = item.context("failed to decode spore")?;
        config
            .hosting
            .apply(&config)
            .await
            .context("failed to apply hosting")?;
        println!("Mycelia Spore: hosting updated for site {}", config.site.id);
    }
    Ok(())
}
